name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y cmake g++

      - name: Create Build Directory
        run: mkdir build

      - name: Go to Build Directory
        run: cd build

      - name: Configure CMake
        run: cmake .

      - name: Build Project
        run: make
      - name: Run executable
        run: ./project
      - name: Clean
        run: make clean-all
